import type { Metadata } from "next";

import "@Styles/globals.css";
import "@Styles/main.css";
import 'lenis/dist/lenis.css'
import MainLayout from "@Layouts/MainLayout";


export const metadata: Metadata = {
  title: "A25 Studio",
  description: "Generated by 20Studio",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
